[2023-02-04T00:21:46.492+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-02-04T00:16:43.599798+00:00 [queued]>
[2023-02-04T00:21:46.502+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-02-04T00:16:43.599798+00:00 [queued]>
[2023-02-04T00:21:46.503+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T00:21:46.504+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-02-04T00:21:46.505+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T00:21:46.521+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): clean_and_transform_data> on 2023-02-04 00:16:43.599798+00:00
[2023-02-04T00:21:46.526+0000] {standard_task_runner.py:54} INFO - Started process 1648 to run task
[2023-02-04T00:21:46.538+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'clean_and_transform_data', 'manual__2023-02-04T00:16:43.599798+00:00', '--job-id', '1293', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmpgdy53bu8']
[2023-02-04T00:21:46.539+0000] {standard_task_runner.py:83} INFO - Job 1293: Subtask clean_and_transform_data
[2023-02-04T00:21:46.540+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-02-04T00:21:46.835+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-02-04T00:16:43.599798+00:00 [running]> on host 9667f615f42a
[2023-02-04T00:21:46.886+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=clean_and_transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T00:16:43.599798+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T00:16:43.599798+00:00
[2023-02-04T00:21:46.902+0000] {logging_mixin.py:117} INFO - The value of the dataframe 1 is :
[2023-02-04T00:21:46.904+0000] {logging_mixin.py:117} INFO - {'address': {'0': '1234 Elm St', '1': '5678 Oak Ave', '2': '1234 Birch Rd'}, 'city': {'0': 'Anytown', '1': 'Othertown', '2': 'Sometown'}, 'zipcode': {'0': 12345, '1': 67890, '2': 54321}, 'price': {'0': 500000, '1': 450000, '2': 425000}, 'bedrooms': {'0': 3, '1': 4, '2': 3}, 'bathrooms': {'0': 2.0, '1': 2.5, '2': 2.0}, 'sqft': {'0': 2000, '1': 2500, '2': 1500}, 'sale_date': {'0': '2022-01-01', '1': '2022-01-02', '2': '2022-01-03'}}
[2023-02-04T00:21:46.905+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 51, in clean_and_transform_data
    df =  pd.ataFrame.from_dict(data_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'ataFrame'
[2023-02-04T00:21:46.918+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=real_estate_data_pipeline, task_id=clean_and_transform_data, execution_date=20230204T001643, start_date=20230204T002146, end_date=20230204T002146
[2023-02-04T00:21:46.934+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1293 for task clean_and_transform_data (module 'pandas' has no attribute 'ataFrame'; 1648)
[2023-02-04T00:21:46.984+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-04T00:21:47.008+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
